name: xysbtn-rss2json

on:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "* * 1 * *"

jobs:
  buildandsubRSS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependency 
        run: npm install
      - name: run index.js
        run: node index.js
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.xysbtndeploy }}
          ARGS: "-rltgoDzvO"
          SOURCE: "json/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/node_modules/"
      